%% Function Header Comment
% Developer: FANG Huangcheng @ PolyU
% Last updated: 2025-01-01
% Email: valy_f@bjtu.edu.cn;huangcheng.fang@polyu.edu.hk
% Website: https://www.researchgate.net/profile/Huangcheng-Fang
% Please do not remove this Header Comment under any circumstances, such as using or modifying this code, or convert this code to another programming language
%This code is automatically generated by EasyUmat.
%Before utilizing this code, users should verify its correctness.
%If this code is used for academic research or any other purpose, please provide appropriate citation or acknowledgment.
%EasyUmat is developed by Huangcheng FANG @ PolyU
%Email: valy_f@bjtu.edu.cn;huangcheng.fang@polyu.edu.hk
%Website: https://www.researchgate.net/profile/Huangcheng-Fang
%============================Input parameter===============================
%elasPara: nx1 vector
%plasPara: nx1 vector
%histPara:  nx1 vector
%otherPara: nxm matrix
%stress: 6x1 vector,[Sx;Sy;Sz;Sxy;Syz;Szx]
%pstrain(plastic strain): 6x1 vector,[PEx;PEy;PEz;PExy;PEyz;PEzx]
%dstrain(strain increment): 6x1 vector,[dEx;dEy;dEz;dExy;dEyz;dEzx]
%==============================Output parameter============================
%Dct(Consistent tangent matrix): 6x6 matrix
%stress: 6x1 vector,[Sx;Sy;Sz;Sxy;Syz;Szx]
%pstrain(plastic strain): 6x1 vector,[PEx;PEy;PEz;PExy;PEyz;PEzx]
%histPara: nx1 vector
%===============================Method=====================================
%Implicit return algorithm; Backward Euler Method
%==========================================================================
%Please do not delete the above text at any time, such as using or modifying this code, or convert this code to another language
 
function [stress,Dct,pstrain,histPara]=Easy_Tresca(elasPara,plasPara,histPara,otherPara,stress,pstrain,dstrain)
%========================Initialize input parameters=======================
E=elasPara(1); niu=elasPara(2);  
c=otherPara(1,2);  
 
%=======================Initialize stress and strain=======================
PEx0=pstrain(1); PEy0=pstrain(2); PEz0=pstrain(3);
PExy0=pstrain(4); PEyz0=pstrain(5); PEzx0=pstrain(6);
Sx0=stress(1); Sy0=stress(2); Sz0=stress(3);
Sxy0=stress(4); Syz0=stress(5); Szx0=stress(6);
dPEx=0; dPEy=0; dPEz=0; dPExy=0; dPEyz=0; dPEzx=0;
PEx=pstrain(1); PEy=pstrain(2); PEz=pstrain(3);
PExy=pstrain(4); PEyz=pstrain(5); PEzx=pstrain(6);

%===========================Update elastic stress==========================
dstrain_elas=dstrain;
[dsigma,D_elastic]=linear_elastic(E,niu,dstrain_elas);
stress_predict=stress+dsigma;

%=====================Update variables related to stress===================
[I1,J2,J3,Lode,sx,sxy,sy,syz,sz,szx]=calculate_stress_invariant(stress_predict);
[S1,S2,S3,s1,s2,s3]=calculate_principal_stress(I1,J2,Lode);

%====================Update characteristic plastic strain====================
dPEEQ=0;

%========================Update user-defined constant======================
s01=s1;
s02=s2;
s03=s3;
adj=0.99999;

%=====================Update user-defined stress variables=================

%=====================Update user-defined strain variables=================

%=========================Update hardening parameters======================

%==========================Update yield function===========================
active_fun=[1>0;s01+s03+2*adj*c-2*s02<=0;s01+s03-2*adj*c-2*s02>=0];
refF=c;
F=zeros(3,1);
if active_fun(1); F(1)=s1 - 2*c - s3;end
if active_fun(2); F(2)=s2 - s3 - c*(adj + 1);end
if active_fun(3); F(3)=s1 - s2 - c*(adj + 1);end

%=============================Elastic output===============================
if max(F)<refF*1e-5
  stress=stress_predict;
  Dct=D_elastic;
  return;
end

%============================Plastic calculation===========================
iternum=0;tol=1e-6;active_num=sum(active_fun,'all');
HPara=[];pLamda=zeros(numel(active_fun),1);
while true
% Calculate derivatives of yield and potential functions
k11=zeros(6,6);k12=[];k21=[];dpstrain=zeros(6,1);
if active_fun(1)
  dFdS=calculate_dF1dS(J2, s1, s3, sx, sxy, sy, syz, sz, szx);
  [dGdS,ddGddS]=calculate_dG1dS(J2, s1, s3, sx, sxy, sy, syz, sz, szx);
  dpstrain=dpstrain+pLamda(1)*dGdS;
  k11=k11+pLamda(1)*ddGddS;
  k12=[k12,dGdS];
  k21=[k21;dFdS.'];
end

if active_fun(2)
  dFdS=calculate_dF2dS(J2, s2, s3, sx, sxy, sy, syz, sz, szx);
  [dGdS,ddGddS]=calculate_dG2dS(J2, s2, s3, sx, sxy, sy, syz, sz, szx);
  dpstrain=dpstrain+pLamda(2)*dGdS;
  k11=k11+pLamda(2)*ddGddS;
  k12=[k12,dGdS];
  k21=[k21;dFdS.'];
end

if active_fun(3)
  dFdS=calculate_dF3dS(J2, s1, s2, sx, sxy, sy, syz, sz, szx);
  [dGdS,ddGddS]=calculate_dG3dS(J2, s1, s2, sx, sxy, sy, syz, sz, szx);
  dpstrain=dpstrain+pLamda(3)*dGdS;
  k11=k11+pLamda(3)*ddGddS;
  k12=[k12,dGdS];
  k21=[k21;dFdS.'];
end

% Update characteristic plastic strain
  dPEEQ=calculate_equivalent_strain(dpstrain);

% Update user-defined strain variables

% Update stress increment
  dstrain_elas=dstrain-dpstrain;
  [dsigma_corrected,D_elastic]=linear_elastic(E,niu,dstrain_elas);

% Calculate residuals
  sigma_res=dsigma_corrected-dsigma;
  F_res=-F(active_fun);
  HPara_res=[];

% Calculate tangent matrix
  Ktang=[eye(6)+D_elastic*k11, D_elastic*k12; k21,  zeros(active_num)];

% Convergence criterion
  if norm(F_res)/refF<tol; break;end

% Update variables
  x=Ktang\[sigma_res;F_res;HPara_res];
  dsigma=dsigma+x(1:6);
  pLamda(active_fun)=pLamda(active_fun)+x(7:6+active_num);
  HPara=HPara+x(7+active_num:end);
  stress_predict=stress+dsigma;

% Update variables related to stress
  [I1,J2,J3,Lode,sx,sxy,sy,syz,sz,szx]=calculate_stress_invariant(stress_predict);
  [S1,S2,S3,s1,s2,s3]=calculate_principal_stress(I1,J2,Lode);

% Update user-defined stress variables

% Update yield function
  active_fun=[1>0;s01+s03+2*adj*c-2*s02<=0;s01+s03-2*adj*c-2*s02>=0];
  active_num=sum(active_fun,'all');
  refF=c;
  F=zeros(3,1);
  if active_fun(1); F(1)=s1 - 2*c - s3;end
  if active_fun(2); F(2)=s2 - s3 - c*(adj + 1);end
  if active_fun(3); F(3)=s1 - s2 - c*(adj + 1);end


% Count
  iternum=iternum+1;
  if iternum>20
    error('Material nonlinear iteration cannot converge in Easy_UMat')
  end
end

%==============================Plastic output==============================
stress=stress+dsigma;
pstrain=pstrain+dpstrain;
Dct=Ktang\[D_elastic;zeros(active_num+0,6)];
Dct=Dct(1:6,1:6);
if abs((s1-s2)/s1)<0.0001
Dct=0.4*Dct+0.6*D_elastic;
end
end

function [dsigmar,D_elastic]=linear_elastic(E,niu,dstrain)
LAM=E/(1+niu);
a=(1-niu)/(1-2*niu)*LAM;
b=niu/(1-2*niu)*LAM;
c=0.5*LAM;
D_elastic=[a, b, b, 0, 0, 0;
b, a, b, 0, 0, 0;
b, b, a, 0, 0, 0;
0, 0, 0, c, 0, 0;
0, 0, 0, 0, c, 0;
0, 0, 0, 0, 0, c;];
dsigmar=D_elastic*dstrain;
end

function [I1,J2,J3,Lode,sx,sxy,sy,syz,sz,szx]=calculate_stress_invariant(stress)
Sx=stress(1); Sy=stress(2); Sz=stress(3);
Sxy=stress(4); Syz=stress(5); Szx=stress(6);
I1=Sx+Sy+Sz; Sm=I1/3;
sx=Sx-Sm; sy=Sy-Sm; sz=Sz-Sm; sxy=Sxy; syz=Syz; szx=Szx;
J2=0.5*(sx.^2+sy.^2+sz.^2)+sxy.^2+syz.^2+szx.^2;
J3=sx*sy*sz+2*sxy*syz*szx-sx*syz.^2-sy*szx.^2-sz*sxy.^2;
temp=-1.5*sqrt(3.0)*J3/J2^1.5;temp=sign(temp)*min(abs(temp),1.0);Lode=asin(temp)/3.0;
end


function [S1,S2,S3,s1,s2,s3]=calculate_principal_stress(I1,J2,Lode)
sm=I1/3;
s1=2*sqrt(J2)/sqrt(3)*sin(Lode+2*pi/3);
s2=2*sqrt(J2)/sqrt(3)*sin(Lode);
s3=2*sqrt(J2)/sqrt(3)*sin(Lode-2*pi/3);
S1=s1+sm;
S2=s2+sm;
S3=s3+sm;
end


function dFdS=calculate_dF1dS(J2, s1, s3, sx, sxy, sy, syz, sz, szx)
dXFdS=[-(J2/3 + s1*sx + sy*sz - syz^2)/(J2 - 3*s1^2), -(J2/3 + s3*sx + sy*sz - syz^2)/(J2 - 3*s3^2);
       -(J2/3 + s1*sy + sx*sz - szx^2)/(J2 - 3*s1^2), -(J2/3 + s3*sy + sx*sz - szx^2)/(J2 - 3*s3^2);
       -(J2/3 + s1*sz + sx*sy - sxy^2)/(J2 - 3*s1^2), -(J2/3 + s3*sz + sx*sy - sxy^2)/(J2 - 3*s3^2);
       -(2*s1*sxy - 2*sxy*sz + 2*syz*szx)/(J2 - 3*s1^2), -(2*s3*sxy - 2*sxy*sz + 2*syz*szx)/(J2 - 3*s3^2);
       -(2*s1*syz - 2*sx*syz + 2*sxy*szx)/(J2 - 3*s1^2), -(2*s3*syz - 2*sx*syz + 2*sxy*szx)/(J2 - 3*s3^2);
       -(2*s1*szx + 2*sxy*syz - 2*sy*szx)/(J2 - 3*s1^2), -(2*s3*szx + 2*sxy*syz - 2*sy*szx)/(J2 - 3*s3^2)];
dFdX=[1;
      -1];
dFdS=dXFdS*dFdX;
end

function dFdS=calculate_dF2dS(J2, s2, s3, sx, sxy, sy, syz, sz, szx)
dXFdS=[-(J2/3 + s2*sx + sy*sz - syz^2)/(J2 - 3*s2^2), -(J2/3 + s3*sx + sy*sz - syz^2)/(J2 - 3*s3^2);
       -(J2/3 + s2*sy + sx*sz - szx^2)/(J2 - 3*s2^2), -(J2/3 + s3*sy + sx*sz - szx^2)/(J2 - 3*s3^2);
       -(J2/3 + s2*sz + sx*sy - sxy^2)/(J2 - 3*s2^2), -(J2/3 + s3*sz + sx*sy - sxy^2)/(J2 - 3*s3^2);
       -(2*s2*sxy - 2*sxy*sz + 2*syz*szx)/(J2 - 3*s2^2), -(2*s3*sxy - 2*sxy*sz + 2*syz*szx)/(J2 - 3*s3^2);
       -(2*s2*syz - 2*sx*syz + 2*sxy*szx)/(J2 - 3*s2^2), -(2*s3*syz - 2*sx*syz + 2*sxy*szx)/(J2 - 3*s3^2);
       -(2*s2*szx + 2*sxy*syz - 2*sy*szx)/(J2 - 3*s2^2), -(2*s3*szx + 2*sxy*syz - 2*sy*szx)/(J2 - 3*s3^2)];
dFdX=[1;
      -1];
dFdS=dXFdS*dFdX;
end

function dFdS=calculate_dF3dS(J2, s1, s2, sx, sxy, sy, syz, sz, szx)
dXFdS=[-(J2/3 + s1*sx + sy*sz - syz^2)/(J2 - 3*s1^2), -(J2/3 + s2*sx + sy*sz - syz^2)/(J2 - 3*s2^2);
       -(J2/3 + s1*sy + sx*sz - szx^2)/(J2 - 3*s1^2), -(J2/3 + s2*sy + sx*sz - szx^2)/(J2 - 3*s2^2);
       -(J2/3 + s1*sz + sx*sy - sxy^2)/(J2 - 3*s1^2), -(J2/3 + s2*sz + sx*sy - sxy^2)/(J2 - 3*s2^2);
       -(2*s1*sxy - 2*sxy*sz + 2*syz*szx)/(J2 - 3*s1^2), -(2*s2*sxy - 2*sxy*sz + 2*syz*szx)/(J2 - 3*s2^2);
       -(2*s1*syz - 2*sx*syz + 2*sxy*szx)/(J2 - 3*s1^2), -(2*s2*syz - 2*sx*syz + 2*sxy*szx)/(J2 - 3*s2^2);
       -(2*s1*szx + 2*sxy*syz - 2*sy*szx)/(J2 - 3*s1^2), -(2*s2*szx + 2*sxy*syz - 2*sy*szx)/(J2 - 3*s2^2)];
dFdX=[1;
      -1];
dFdS=dXFdS*dFdX;
end

function [dGdS,ddGddS]=calculate_dG1dS(J2, s1, s3, sx, sxy, sy, syz, sz, szx)
dXGdS=[-(J2/3 + s1*sx + sy*sz - syz^2)/(J2 - 3*s1^2), -(J2/3 + s3*sx + sy*sz - syz^2)/(J2 - 3*s3^2);
       -(J2/3 + s1*sy + sx*sz - szx^2)/(J2 - 3*s1^2), -(J2/3 + s3*sy + sx*sz - szx^2)/(J2 - 3*s3^2);
       -(J2/3 + s1*sz + sx*sy - sxy^2)/(J2 - 3*s1^2), -(J2/3 + s3*sz + sx*sy - sxy^2)/(J2 - 3*s3^2);
       -(2*s1*sxy - 2*sxy*sz + 2*syz*szx)/(J2 - 3*s1^2), -(2*s3*sxy - 2*sxy*sz + 2*syz*szx)/(J2 - 3*s3^2);
       -(2*s1*syz - 2*sx*syz + 2*sxy*szx)/(J2 - 3*s1^2), -(2*s3*syz - 2*sx*syz + 2*sxy*szx)/(J2 - 3*s3^2);
       -(2*s1*szx + 2*sxy*syz - 2*sy*szx)/(J2 - 3*s1^2), -(2*s3*szx + 2*sxy*syz - 2*sy*szx)/(J2 - 3*s3^2)];
dGdX=[1;
      -1];
dGdS=dXGdS*dGdX;

ddGddX=[0, 0;
        0, 0];
ddXGddS1=[sy/(3*(J2 - 3*s1^2)) - (2*s1)/(3*(J2 - 3*s1^2)) + sz/(3*(J2 - 3*s1^2)) - sx*(1/(3*(J2 - 3*s1^2)) - (J2/3 + s1*sx + sy*sz - syz^2)/(J2 - 3*s1^2)^2) + ((sx/(J2 - 3*s1^2) + (6*s1*(J2/3 + s1*sx + sy*sz - syz^2))/(J2 - 3*s1^2)^2)*(J2/3 + s1*sx + sy*sz - syz^2))/(J2 - 3*s1^2), s1/(3*(J2 - 3*s1^2)) + sy/(3*(J2 - 3*s1^2)) - (2*sz)/(3*(J2 - 3*s1^2)) - sy*(1/(3*(J2 - 3*s1^2)) - (J2/3 + s1*sx + sy*sz - syz^2)/(J2 - 3*s1^2)^2) + ((sx/(J2 - 3*s1^2) + (6*s1*(J2/3 + s1*sx + sy*sz - syz^2))/(J2 - 3*s1^2)^2)*(J2/3 + s1*sy + sx*sz - szx^2))/(J2 - 3*s1^2), s1/(3*(J2 - 3*s1^2)) - (2*sy)/(3*(J2 - 3*s1^2)) + sz/(3*(J2 - 3*s1^2)) - sz*(1/(3*(J2 - 3*s1^2)) - (J2/3 + s1*sx + sy*sz - syz^2)/(J2 - 3*s1^2)^2) + ((sx/(J2 - 3*s1^2) + (6*s1*(J2/3 + s1*sx + sy*sz - syz^2))/(J2 - 3*s1^2)^2)*(J2/3 + s1*sz + sx*sy - sxy^2))/(J2 - 3*s1^2), ((sx/(J2 - 3*s1^2) + (6*s1*(J2/3 + s1*sx + sy*sz - syz^2))/(J2 - 3*s1^2)^2)*(2*s1*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s1^2) - 2*sxy*(1/(3*(J2 - 3*s1^2)) - (J2/3 + s1*sx + sy*sz - syz^2)/(J2 - 3*s1^2)^2), (2*syz)/(J2 - 3*s1^2) - 2*syz*(1/(3*(J2 - 3*s1^2)) - (J2/3 + s1*sx + sy*sz - syz^2)/(J2 - 3*s1^2)^2) + ((sx/(J2 - 3*s1^2) + (6*s1*(J2/3 + s1*sx + sy*sz - syz^2))/(J2 - 3*s1^2)^2)*(2*s1*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s1^2), ((sx/(J2 - 3*s1^2) + (6*s1*(J2/3 + s1*sx + sy*sz - syz^2))/(J2 - 3*s1^2)^2)*(2*s1*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s1^2) - 2*szx*(1/(3*(J2 - 3*s1^2)) - (J2/3 + s1*sx + sy*sz - syz^2)/(J2 - 3*s1^2)^2);
         s1/(3*(J2 - 3*s1^2)) + sx/(3*(J2 - 3*s1^2)) - (2*sz)/(3*(J2 - 3*s1^2)) - sx*(1/(3*(J2 - 3*s1^2)) - (J2/3 + s1*sy + sx*sz - szx^2)/(J2 - 3*s1^2)^2) + ((sy/(J2 - 3*s1^2) + (6*s1*(J2/3 + s1*sy + sx*sz - szx^2))/(J2 - 3*s1^2)^2)*(J2/3 + s1*sx + sy*sz - syz^2))/(J2 - 3*s1^2), sx/(3*(J2 - 3*s1^2)) - (2*s1)/(3*(J2 - 3*s1^2)) + sz/(3*(J2 - 3*s1^2)) - sy*(1/(3*(J2 - 3*s1^2)) - (J2/3 + s1*sy + sx*sz - szx^2)/(J2 - 3*s1^2)^2) + ((sy/(J2 - 3*s1^2) + (6*s1*(J2/3 + s1*sy + sx*sz - szx^2))/(J2 - 3*s1^2)^2)*(J2/3 + s1*sy + sx*sz - szx^2))/(J2 - 3*s1^2), s1/(3*(J2 - 3*s1^2)) - (2*sx)/(3*(J2 - 3*s1^2)) + sz/(3*(J2 - 3*s1^2)) - sz*(1/(3*(J2 - 3*s1^2)) - (J2/3 + s1*sy + sx*sz - szx^2)/(J2 - 3*s1^2)^2) + ((sy/(J2 - 3*s1^2) + (6*s1*(J2/3 + s1*sy + sx*sz - szx^2))/(J2 - 3*s1^2)^2)*(J2/3 + s1*sz + sx*sy - sxy^2))/(J2 - 3*s1^2), ((sy/(J2 - 3*s1^2) + (6*s1*(J2/3 + s1*sy + sx*sz - szx^2))/(J2 - 3*s1^2)^2)*(2*s1*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s1^2) - 2*sxy*(1/(3*(J2 - 3*s1^2)) - (J2/3 + s1*sy + sx*sz - szx^2)/(J2 - 3*s1^2)^2), ((sy/(J2 - 3*s1^2) + (6*s1*(J2/3 + s1*sy + sx*sz - szx^2))/(J2 - 3*s1^2)^2)*(2*s1*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s1^2) - 2*syz*(1/(3*(J2 - 3*s1^2)) - (J2/3 + s1*sy + sx*sz - szx^2)/(J2 - 3*s1^2)^2), (2*szx)/(J2 - 3*s1^2) - 2*szx*(1/(3*(J2 - 3*s1^2)) - (J2/3 + s1*sy + sx*sz - szx^2)/(J2 - 3*s1^2)^2) + ((sy/(J2 - 3*s1^2) + (6*s1*(J2/3 + s1*sy + sx*sz - szx^2))/(J2 - 3*s1^2)^2)*(2*s1*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s1^2);
         s1/(3*(J2 - 3*s1^2)) + sx/(3*(J2 - 3*s1^2)) - (2*sy)/(3*(J2 - 3*s1^2)) - sx*(1/(3*(J2 - 3*s1^2)) - (J2/3 + s1*sz + sx*sy - sxy^2)/(J2 - 3*s1^2)^2) + ((sz/(J2 - 3*s1^2) + (6*s1*(J2/3 + s1*sz + sx*sy - sxy^2))/(J2 - 3*s1^2)^2)*(J2/3 + s1*sx + sy*sz - syz^2))/(J2 - 3*s1^2), s1/(3*(J2 - 3*s1^2)) - (2*sx)/(3*(J2 - 3*s1^2)) + sy/(3*(J2 - 3*s1^2)) - sy*(1/(3*(J2 - 3*s1^2)) - (J2/3 + s1*sz + sx*sy - sxy^2)/(J2 - 3*s1^2)^2) + ((sz/(J2 - 3*s1^2) + (6*s1*(J2/3 + s1*sz + sx*sy - sxy^2))/(J2 - 3*s1^2)^2)*(J2/3 + s1*sy + sx*sz - szx^2))/(J2 - 3*s1^2), sx/(3*(J2 - 3*s1^2)) - (2*s1)/(3*(J2 - 3*s1^2)) + sy/(3*(J2 - 3*s1^2)) - sz*(1/(3*(J2 - 3*s1^2)) - (J2/3 + s1*sz + sx*sy - sxy^2)/(J2 - 3*s1^2)^2) + ((sz/(J2 - 3*s1^2) + (6*s1*(J2/3 + s1*sz + sx*sy - sxy^2))/(J2 - 3*s1^2)^2)*(J2/3 + s1*sz + sx*sy - sxy^2))/(J2 - 3*s1^2), (2*sxy)/(J2 - 3*s1^2) - 2*sxy*(1/(3*(J2 - 3*s1^2)) - (J2/3 + s1*sz + sx*sy - sxy^2)/(J2 - 3*s1^2)^2) + ((sz/(J2 - 3*s1^2) + (6*s1*(J2/3 + s1*sz + sx*sy - sxy^2))/(J2 - 3*s1^2)^2)*(2*s1*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s1^2), ((sz/(J2 - 3*s1^2) + (6*s1*(J2/3 + s1*sz + sx*sy - sxy^2))/(J2 - 3*s1^2)^2)*(2*s1*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s1^2) - 2*syz*(1/(3*(J2 - 3*s1^2)) - (J2/3 + s1*sz + sx*sy - sxy^2)/(J2 - 3*s1^2)^2), ((sz/(J2 - 3*s1^2) + (6*s1*(J2/3 + s1*sz + sx*sy - sxy^2))/(J2 - 3*s1^2)^2)*(2*s1*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s1^2) - 2*szx*(1/(3*(J2 - 3*s1^2)) - (J2/3 + s1*sz + sx*sy - sxy^2)/(J2 - 3*s1^2)^2);
         (((2*sxy)/(J2 - 3*s1^2) + (6*s1*(2*s1*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s1^2)^2)*(J2/3 + s1*sx + sy*sz - syz^2))/(J2 - 3*s1^2) - (2*sxy)/(3*(J2 - 3*s1^2)) + (sx*(2*s1*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s1^2)^2, (((2*sxy)/(J2 - 3*s1^2) + (6*s1*(2*s1*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s1^2)^2)*(J2/3 + s1*sy + sx*sz - szx^2))/(J2 - 3*s1^2) - (2*sxy)/(3*(J2 - 3*s1^2)) + (sy*(2*s1*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s1^2)^2, (4*sxy)/(3*(J2 - 3*s1^2)) + (((2*sxy)/(J2 - 3*s1^2) + (6*s1*(2*s1*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s1^2)^2)*(J2/3 + s1*sz + sx*sy - sxy^2))/(J2 - 3*s1^2) + (sz*(2*s1*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s1^2)^2, (2*sxy*(2*s1*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s1^2)^2 - (2*s1 - 2*sz)/(J2 - 3*s1^2) + (((2*sxy)/(J2 - 3*s1^2) + (6*s1*(2*s1*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s1^2)^2)*(2*s1*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s1^2), (2*syz*(2*s1*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s1^2)^2 - (2*szx)/(J2 - 3*s1^2) + (((2*sxy)/(J2 - 3*s1^2) + (6*s1*(2*s1*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s1^2)^2)*(2*s1*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s1^2), (2*szx*(2*s1*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s1^2)^2 - (2*syz)/(J2 - 3*s1^2) + (((2*sxy)/(J2 - 3*s1^2) + (6*s1*(2*s1*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s1^2)^2)*(2*s1*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s1^2);
         (4*syz)/(3*(J2 - 3*s1^2)) + (((2*syz)/(J2 - 3*s1^2) + (6*s1*(2*s1*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s1^2)^2)*(J2/3 + s1*sx + sy*sz - syz^2))/(J2 - 3*s1^2) + (sx*(2*s1*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s1^2)^2, (((2*syz)/(J2 - 3*s1^2) + (6*s1*(2*s1*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s1^2)^2)*(J2/3 + s1*sy + sx*sz - szx^2))/(J2 - 3*s1^2) - (2*syz)/(3*(J2 - 3*s1^2)) + (sy*(2*s1*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s1^2)^2, (((2*syz)/(J2 - 3*s1^2) + (6*s1*(2*s1*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s1^2)^2)*(J2/3 + s1*sz + sx*sy - sxy^2))/(J2 - 3*s1^2) - (2*syz)/(3*(J2 - 3*s1^2)) + (sz*(2*s1*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s1^2)^2, (2*sxy*(2*s1*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s1^2)^2 - (2*szx)/(J2 - 3*s1^2) + (((2*syz)/(J2 - 3*s1^2) + (6*s1*(2*s1*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s1^2)^2)*(2*s1*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s1^2), (2*syz*(2*s1*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s1^2)^2 - (2*s1 - 2*sx)/(J2 - 3*s1^2) + (((2*syz)/(J2 - 3*s1^2) + (6*s1*(2*s1*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s1^2)^2)*(2*s1*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s1^2), (2*szx*(2*s1*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s1^2)^2 - (2*sxy)/(J2 - 3*s1^2) + (((2*syz)/(J2 - 3*s1^2) + (6*s1*(2*s1*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s1^2)^2)*(2*s1*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s1^2);
         (((2*szx)/(J2 - 3*s1^2) + (6*s1*(2*s1*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s1^2)^2)*(J2/3 + s1*sx + sy*sz - syz^2))/(J2 - 3*s1^2) - (2*szx)/(3*(J2 - 3*s1^2)) + (sx*(2*s1*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s1^2)^2, (4*szx)/(3*(J2 - 3*s1^2)) + (((2*szx)/(J2 - 3*s1^2) + (6*s1*(2*s1*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s1^2)^2)*(J2/3 + s1*sy + sx*sz - szx^2))/(J2 - 3*s1^2) + (sy*(2*s1*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s1^2)^2, (((2*szx)/(J2 - 3*s1^2) + (6*s1*(2*s1*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s1^2)^2)*(J2/3 + s1*sz + sx*sy - sxy^2))/(J2 - 3*s1^2) - (2*szx)/(3*(J2 - 3*s1^2)) + (sz*(2*s1*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s1^2)^2, (2*sxy*(2*s1*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s1^2)^2 - (2*syz)/(J2 - 3*s1^2) + (((2*szx)/(J2 - 3*s1^2) + (6*s1*(2*s1*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s1^2)^2)*(2*s1*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s1^2), (2*syz*(2*s1*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s1^2)^2 - (2*sxy)/(J2 - 3*s1^2) + (((2*szx)/(J2 - 3*s1^2) + (6*s1*(2*s1*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s1^2)^2)*(2*s1*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s1^2), (2*szx*(2*s1*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s1^2)^2 - (2*s1 - 2*sy)/(J2 - 3*s1^2) + (((2*szx)/(J2 - 3*s1^2) + (6*s1*(2*s1*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s1^2)^2)*(2*s1*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s1^2)];
ddXGddS2=[sy/(3*(J2 - 3*s3^2)) - (2*s3)/(3*(J2 - 3*s3^2)) + sz/(3*(J2 - 3*s3^2)) - sx*(1/(3*(J2 - 3*s3^2)) - (J2/3 + s3*sx + sy*sz - syz^2)/(J2 - 3*s3^2)^2) + ((sx/(J2 - 3*s3^2) + (6*s3*(J2/3 + s3*sx + sy*sz - syz^2))/(J2 - 3*s3^2)^2)*(J2/3 + s3*sx + sy*sz - syz^2))/(J2 - 3*s3^2), s3/(3*(J2 - 3*s3^2)) + sy/(3*(J2 - 3*s3^2)) - (2*sz)/(3*(J2 - 3*s3^2)) - sy*(1/(3*(J2 - 3*s3^2)) - (J2/3 + s3*sx + sy*sz - syz^2)/(J2 - 3*s3^2)^2) + ((sx/(J2 - 3*s3^2) + (6*s3*(J2/3 + s3*sx + sy*sz - syz^2))/(J2 - 3*s3^2)^2)*(J2/3 + s3*sy + sx*sz - szx^2))/(J2 - 3*s3^2), s3/(3*(J2 - 3*s3^2)) - (2*sy)/(3*(J2 - 3*s3^2)) + sz/(3*(J2 - 3*s3^2)) - sz*(1/(3*(J2 - 3*s3^2)) - (J2/3 + s3*sx + sy*sz - syz^2)/(J2 - 3*s3^2)^2) + ((sx/(J2 - 3*s3^2) + (6*s3*(J2/3 + s3*sx + sy*sz - syz^2))/(J2 - 3*s3^2)^2)*(J2/3 + s3*sz + sx*sy - sxy^2))/(J2 - 3*s3^2), ((sx/(J2 - 3*s3^2) + (6*s3*(J2/3 + s3*sx + sy*sz - syz^2))/(J2 - 3*s3^2)^2)*(2*s3*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s3^2) - 2*sxy*(1/(3*(J2 - 3*s3^2)) - (J2/3 + s3*sx + sy*sz - syz^2)/(J2 - 3*s3^2)^2), (2*syz)/(J2 - 3*s3^2) - 2*syz*(1/(3*(J2 - 3*s3^2)) - (J2/3 + s3*sx + sy*sz - syz^2)/(J2 - 3*s3^2)^2) + ((sx/(J2 - 3*s3^2) + (6*s3*(J2/3 + s3*sx + sy*sz - syz^2))/(J2 - 3*s3^2)^2)*(2*s3*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s3^2), ((sx/(J2 - 3*s3^2) + (6*s3*(J2/3 + s3*sx + sy*sz - syz^2))/(J2 - 3*s3^2)^2)*(2*s3*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s3^2) - 2*szx*(1/(3*(J2 - 3*s3^2)) - (J2/3 + s3*sx + sy*sz - syz^2)/(J2 - 3*s3^2)^2);
         s3/(3*(J2 - 3*s3^2)) + sx/(3*(J2 - 3*s3^2)) - (2*sz)/(3*(J2 - 3*s3^2)) - sx*(1/(3*(J2 - 3*s3^2)) - (J2/3 + s3*sy + sx*sz - szx^2)/(J2 - 3*s3^2)^2) + ((sy/(J2 - 3*s3^2) + (6*s3*(J2/3 + s3*sy + sx*sz - szx^2))/(J2 - 3*s3^2)^2)*(J2/3 + s3*sx + sy*sz - syz^2))/(J2 - 3*s3^2), sx/(3*(J2 - 3*s3^2)) - (2*s3)/(3*(J2 - 3*s3^2)) + sz/(3*(J2 - 3*s3^2)) - sy*(1/(3*(J2 - 3*s3^2)) - (J2/3 + s3*sy + sx*sz - szx^2)/(J2 - 3*s3^2)^2) + ((sy/(J2 - 3*s3^2) + (6*s3*(J2/3 + s3*sy + sx*sz - szx^2))/(J2 - 3*s3^2)^2)*(J2/3 + s3*sy + sx*sz - szx^2))/(J2 - 3*s3^2), s3/(3*(J2 - 3*s3^2)) - (2*sx)/(3*(J2 - 3*s3^2)) + sz/(3*(J2 - 3*s3^2)) - sz*(1/(3*(J2 - 3*s3^2)) - (J2/3 + s3*sy + sx*sz - szx^2)/(J2 - 3*s3^2)^2) + ((sy/(J2 - 3*s3^2) + (6*s3*(J2/3 + s3*sy + sx*sz - szx^2))/(J2 - 3*s3^2)^2)*(J2/3 + s3*sz + sx*sy - sxy^2))/(J2 - 3*s3^2), ((sy/(J2 - 3*s3^2) + (6*s3*(J2/3 + s3*sy + sx*sz - szx^2))/(J2 - 3*s3^2)^2)*(2*s3*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s3^2) - 2*sxy*(1/(3*(J2 - 3*s3^2)) - (J2/3 + s3*sy + sx*sz - szx^2)/(J2 - 3*s3^2)^2), ((sy/(J2 - 3*s3^2) + (6*s3*(J2/3 + s3*sy + sx*sz - szx^2))/(J2 - 3*s3^2)^2)*(2*s3*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s3^2) - 2*syz*(1/(3*(J2 - 3*s3^2)) - (J2/3 + s3*sy + sx*sz - szx^2)/(J2 - 3*s3^2)^2), (2*szx)/(J2 - 3*s3^2) - 2*szx*(1/(3*(J2 - 3*s3^2)) - (J2/3 + s3*sy + sx*sz - szx^2)/(J2 - 3*s3^2)^2) + ((sy/(J2 - 3*s3^2) + (6*s3*(J2/3 + s3*sy + sx*sz - szx^2))/(J2 - 3*s3^2)^2)*(2*s3*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s3^2);
         s3/(3*(J2 - 3*s3^2)) + sx/(3*(J2 - 3*s3^2)) - (2*sy)/(3*(J2 - 3*s3^2)) - sx*(1/(3*(J2 - 3*s3^2)) - (J2/3 + s3*sz + sx*sy - sxy^2)/(J2 - 3*s3^2)^2) + ((sz/(J2 - 3*s3^2) + (6*s3*(J2/3 + s3*sz + sx*sy - sxy^2))/(J2 - 3*s3^2)^2)*(J2/3 + s3*sx + sy*sz - syz^2))/(J2 - 3*s3^2), s3/(3*(J2 - 3*s3^2)) - (2*sx)/(3*(J2 - 3*s3^2)) + sy/(3*(J2 - 3*s3^2)) - sy*(1/(3*(J2 - 3*s3^2)) - (J2/3 + s3*sz + sx*sy - sxy^2)/(J2 - 3*s3^2)^2) + ((sz/(J2 - 3*s3^2) + (6*s3*(J2/3 + s3*sz + sx*sy - sxy^2))/(J2 - 3*s3^2)^2)*(J2/3 + s3*sy + sx*sz - szx^2))/(J2 - 3*s3^2), sx/(3*(J2 - 3*s3^2)) - (2*s3)/(3*(J2 - 3*s3^2)) + sy/(3*(J2 - 3*s3^2)) - sz*(1/(3*(J2 - 3*s3^2)) - (J2/3 + s3*sz + sx*sy - sxy^2)/(J2 - 3*s3^2)^2) + ((sz/(J2 - 3*s3^2) + (6*s3*(J2/3 + s3*sz + sx*sy - sxy^2))/(J2 - 3*s3^2)^2)*(J2/3 + s3*sz + sx*sy - sxy^2))/(J2 - 3*s3^2), (2*sxy)/(J2 - 3*s3^2) - 2*sxy*(1/(3*(J2 - 3*s3^2)) - (J2/3 + s3*sz + sx*sy - sxy^2)/(J2 - 3*s3^2)^2) + ((sz/(J2 - 3*s3^2) + (6*s3*(J2/3 + s3*sz + sx*sy - sxy^2))/(J2 - 3*s3^2)^2)*(2*s3*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s3^2), ((sz/(J2 - 3*s3^2) + (6*s3*(J2/3 + s3*sz + sx*sy - sxy^2))/(J2 - 3*s3^2)^2)*(2*s3*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s3^2) - 2*syz*(1/(3*(J2 - 3*s3^2)) - (J2/3 + s3*sz + sx*sy - sxy^2)/(J2 - 3*s3^2)^2), ((sz/(J2 - 3*s3^2) + (6*s3*(J2/3 + s3*sz + sx*sy - sxy^2))/(J2 - 3*s3^2)^2)*(2*s3*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s3^2) - 2*szx*(1/(3*(J2 - 3*s3^2)) - (J2/3 + s3*sz + sx*sy - sxy^2)/(J2 - 3*s3^2)^2);
         (((2*sxy)/(J2 - 3*s3^2) + (6*s3*(2*s3*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s3^2)^2)*(J2/3 + s3*sx + sy*sz - syz^2))/(J2 - 3*s3^2) - (2*sxy)/(3*(J2 - 3*s3^2)) + (sx*(2*s3*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s3^2)^2, (((2*sxy)/(J2 - 3*s3^2) + (6*s3*(2*s3*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s3^2)^2)*(J2/3 + s3*sy + sx*sz - szx^2))/(J2 - 3*s3^2) - (2*sxy)/(3*(J2 - 3*s3^2)) + (sy*(2*s3*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s3^2)^2, (4*sxy)/(3*(J2 - 3*s3^2)) + (((2*sxy)/(J2 - 3*s3^2) + (6*s3*(2*s3*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s3^2)^2)*(J2/3 + s3*sz + sx*sy - sxy^2))/(J2 - 3*s3^2) + (sz*(2*s3*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s3^2)^2, (2*sxy*(2*s3*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s3^2)^2 - (2*s3 - 2*sz)/(J2 - 3*s3^2) + (((2*sxy)/(J2 - 3*s3^2) + (6*s3*(2*s3*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s3^2)^2)*(2*s3*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s3^2), (2*syz*(2*s3*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s3^2)^2 - (2*szx)/(J2 - 3*s3^2) + (((2*sxy)/(J2 - 3*s3^2) + (6*s3*(2*s3*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s3^2)^2)*(2*s3*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s3^2), (2*szx*(2*s3*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s3^2)^2 - (2*syz)/(J2 - 3*s3^2) + (((2*sxy)/(J2 - 3*s3^2) + (6*s3*(2*s3*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s3^2)^2)*(2*s3*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s3^2);
         (4*syz)/(3*(J2 - 3*s3^2)) + (((2*syz)/(J2 - 3*s3^2) + (6*s3*(2*s3*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s3^2)^2)*(J2/3 + s3*sx + sy*sz - syz^2))/(J2 - 3*s3^2) + (sx*(2*s3*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s3^2)^2, (((2*syz)/(J2 - 3*s3^2) + (6*s3*(2*s3*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s3^2)^2)*(J2/3 + s3*sy + sx*sz - szx^2))/(J2 - 3*s3^2) - (2*syz)/(3*(J2 - 3*s3^2)) + (sy*(2*s3*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s3^2)^2, (((2*syz)/(J2 - 3*s3^2) + (6*s3*(2*s3*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s3^2)^2)*(J2/3 + s3*sz + sx*sy - sxy^2))/(J2 - 3*s3^2) - (2*syz)/(3*(J2 - 3*s3^2)) + (sz*(2*s3*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s3^2)^2, (2*sxy*(2*s3*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s3^2)^2 - (2*szx)/(J2 - 3*s3^2) + (((2*syz)/(J2 - 3*s3^2) + (6*s3*(2*s3*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s3^2)^2)*(2*s3*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s3^2), (2*syz*(2*s3*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s3^2)^2 - (2*s3 - 2*sx)/(J2 - 3*s3^2) + (((2*syz)/(J2 - 3*s3^2) + (6*s3*(2*s3*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s3^2)^2)*(2*s3*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s3^2), (2*szx*(2*s3*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s3^2)^2 - (2*sxy)/(J2 - 3*s3^2) + (((2*syz)/(J2 - 3*s3^2) + (6*s3*(2*s3*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s3^2)^2)*(2*s3*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s3^2);
         (((2*szx)/(J2 - 3*s3^2) + (6*s3*(2*s3*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s3^2)^2)*(J2/3 + s3*sx + sy*sz - syz^2))/(J2 - 3*s3^2) - (2*szx)/(3*(J2 - 3*s3^2)) + (sx*(2*s3*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s3^2)^2, (4*szx)/(3*(J2 - 3*s3^2)) + (((2*szx)/(J2 - 3*s3^2) + (6*s3*(2*s3*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s3^2)^2)*(J2/3 + s3*sy + sx*sz - szx^2))/(J2 - 3*s3^2) + (sy*(2*s3*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s3^2)^2, (((2*szx)/(J2 - 3*s3^2) + (6*s3*(2*s3*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s3^2)^2)*(J2/3 + s3*sz + sx*sy - sxy^2))/(J2 - 3*s3^2) - (2*szx)/(3*(J2 - 3*s3^2)) + (sz*(2*s3*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s3^2)^2, (2*sxy*(2*s3*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s3^2)^2 - (2*syz)/(J2 - 3*s3^2) + (((2*szx)/(J2 - 3*s3^2) + (6*s3*(2*s3*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s3^2)^2)*(2*s3*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s3^2), (2*syz*(2*s3*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s3^2)^2 - (2*sxy)/(J2 - 3*s3^2) + (((2*szx)/(J2 - 3*s3^2) + (6*s3*(2*s3*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s3^2)^2)*(2*s3*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s3^2), (2*szx*(2*s3*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s3^2)^2 - (2*s3 - 2*sy)/(J2 - 3*s3^2) + (((2*szx)/(J2 - 3*s3^2) + (6*s3*(2*s3*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s3^2)^2)*(2*s3*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s3^2)];
ddGddS=dXGdS*ddGddX*dXGdS.'+ddXGddS1*dGdX(1)+ddXGddS2*dGdX(2);
end

function [dGdS,ddGddS]=calculate_dG2dS(J2, s2, s3, sx, sxy, sy, syz, sz, szx)
dXGdS=[-(J2/3 + s2*sx + sy*sz - syz^2)/(J2 - 3*s2^2), -(J2/3 + s3*sx + sy*sz - syz^2)/(J2 - 3*s3^2);
       -(J2/3 + s2*sy + sx*sz - szx^2)/(J2 - 3*s2^2), -(J2/3 + s3*sy + sx*sz - szx^2)/(J2 - 3*s3^2);
       -(J2/3 + s2*sz + sx*sy - sxy^2)/(J2 - 3*s2^2), -(J2/3 + s3*sz + sx*sy - sxy^2)/(J2 - 3*s3^2);
       -(2*s2*sxy - 2*sxy*sz + 2*syz*szx)/(J2 - 3*s2^2), -(2*s3*sxy - 2*sxy*sz + 2*syz*szx)/(J2 - 3*s3^2);
       -(2*s2*syz - 2*sx*syz + 2*sxy*szx)/(J2 - 3*s2^2), -(2*s3*syz - 2*sx*syz + 2*sxy*szx)/(J2 - 3*s3^2);
       -(2*s2*szx + 2*sxy*syz - 2*sy*szx)/(J2 - 3*s2^2), -(2*s3*szx + 2*sxy*syz - 2*sy*szx)/(J2 - 3*s3^2)];
dGdX=[1;
      -1];
dGdS=dXGdS*dGdX;

ddGddX=[0, 0;
        0, 0];
ddXGddS1=[sy/(3*(J2 - 3*s2^2)) - (2*s2)/(3*(J2 - 3*s2^2)) + sz/(3*(J2 - 3*s2^2)) - sx*(1/(3*(J2 - 3*s2^2)) - (J2/3 + s2*sx + sy*sz - syz^2)/(J2 - 3*s2^2)^2) + ((sx/(J2 - 3*s2^2) + (6*s2*(J2/3 + s2*sx + sy*sz - syz^2))/(J2 - 3*s2^2)^2)*(J2/3 + s2*sx + sy*sz - syz^2))/(J2 - 3*s2^2), s2/(3*(J2 - 3*s2^2)) + sy/(3*(J2 - 3*s2^2)) - (2*sz)/(3*(J2 - 3*s2^2)) - sy*(1/(3*(J2 - 3*s2^2)) - (J2/3 + s2*sx + sy*sz - syz^2)/(J2 - 3*s2^2)^2) + ((sx/(J2 - 3*s2^2) + (6*s2*(J2/3 + s2*sx + sy*sz - syz^2))/(J2 - 3*s2^2)^2)*(J2/3 + s2*sy + sx*sz - szx^2))/(J2 - 3*s2^2), s2/(3*(J2 - 3*s2^2)) - (2*sy)/(3*(J2 - 3*s2^2)) + sz/(3*(J2 - 3*s2^2)) - sz*(1/(3*(J2 - 3*s2^2)) - (J2/3 + s2*sx + sy*sz - syz^2)/(J2 - 3*s2^2)^2) + ((sx/(J2 - 3*s2^2) + (6*s2*(J2/3 + s2*sx + sy*sz - syz^2))/(J2 - 3*s2^2)^2)*(J2/3 + s2*sz + sx*sy - sxy^2))/(J2 - 3*s2^2), ((sx/(J2 - 3*s2^2) + (6*s2*(J2/3 + s2*sx + sy*sz - syz^2))/(J2 - 3*s2^2)^2)*(2*s2*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s2^2) - 2*sxy*(1/(3*(J2 - 3*s2^2)) - (J2/3 + s2*sx + sy*sz - syz^2)/(J2 - 3*s2^2)^2), (2*syz)/(J2 - 3*s2^2) - 2*syz*(1/(3*(J2 - 3*s2^2)) - (J2/3 + s2*sx + sy*sz - syz^2)/(J2 - 3*s2^2)^2) + ((sx/(J2 - 3*s2^2) + (6*s2*(J2/3 + s2*sx + sy*sz - syz^2))/(J2 - 3*s2^2)^2)*(2*s2*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s2^2), ((sx/(J2 - 3*s2^2) + (6*s2*(J2/3 + s2*sx + sy*sz - syz^2))/(J2 - 3*s2^2)^2)*(2*s2*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s2^2) - 2*szx*(1/(3*(J2 - 3*s2^2)) - (J2/3 + s2*sx + sy*sz - syz^2)/(J2 - 3*s2^2)^2);
         s2/(3*(J2 - 3*s2^2)) + sx/(3*(J2 - 3*s2^2)) - (2*sz)/(3*(J2 - 3*s2^2)) - sx*(1/(3*(J2 - 3*s2^2)) - (J2/3 + s2*sy + sx*sz - szx^2)/(J2 - 3*s2^2)^2) + ((sy/(J2 - 3*s2^2) + (6*s2*(J2/3 + s2*sy + sx*sz - szx^2))/(J2 - 3*s2^2)^2)*(J2/3 + s2*sx + sy*sz - syz^2))/(J2 - 3*s2^2), sx/(3*(J2 - 3*s2^2)) - (2*s2)/(3*(J2 - 3*s2^2)) + sz/(3*(J2 - 3*s2^2)) - sy*(1/(3*(J2 - 3*s2^2)) - (J2/3 + s2*sy + sx*sz - szx^2)/(J2 - 3*s2^2)^2) + ((sy/(J2 - 3*s2^2) + (6*s2*(J2/3 + s2*sy + sx*sz - szx^2))/(J2 - 3*s2^2)^2)*(J2/3 + s2*sy + sx*sz - szx^2))/(J2 - 3*s2^2), s2/(3*(J2 - 3*s2^2)) - (2*sx)/(3*(J2 - 3*s2^2)) + sz/(3*(J2 - 3*s2^2)) - sz*(1/(3*(J2 - 3*s2^2)) - (J2/3 + s2*sy + sx*sz - szx^2)/(J2 - 3*s2^2)^2) + ((sy/(J2 - 3*s2^2) + (6*s2*(J2/3 + s2*sy + sx*sz - szx^2))/(J2 - 3*s2^2)^2)*(J2/3 + s2*sz + sx*sy - sxy^2))/(J2 - 3*s2^2), ((sy/(J2 - 3*s2^2) + (6*s2*(J2/3 + s2*sy + sx*sz - szx^2))/(J2 - 3*s2^2)^2)*(2*s2*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s2^2) - 2*sxy*(1/(3*(J2 - 3*s2^2)) - (J2/3 + s2*sy + sx*sz - szx^2)/(J2 - 3*s2^2)^2), ((sy/(J2 - 3*s2^2) + (6*s2*(J2/3 + s2*sy + sx*sz - szx^2))/(J2 - 3*s2^2)^2)*(2*s2*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s2^2) - 2*syz*(1/(3*(J2 - 3*s2^2)) - (J2/3 + s2*sy + sx*sz - szx^2)/(J2 - 3*s2^2)^2), (2*szx)/(J2 - 3*s2^2) - 2*szx*(1/(3*(J2 - 3*s2^2)) - (J2/3 + s2*sy + sx*sz - szx^2)/(J2 - 3*s2^2)^2) + ((sy/(J2 - 3*s2^2) + (6*s2*(J2/3 + s2*sy + sx*sz - szx^2))/(J2 - 3*s2^2)^2)*(2*s2*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s2^2);
         s2/(3*(J2 - 3*s2^2)) + sx/(3*(J2 - 3*s2^2)) - (2*sy)/(3*(J2 - 3*s2^2)) - sx*(1/(3*(J2 - 3*s2^2)) - (J2/3 + s2*sz + sx*sy - sxy^2)/(J2 - 3*s2^2)^2) + ((sz/(J2 - 3*s2^2) + (6*s2*(J2/3 + s2*sz + sx*sy - sxy^2))/(J2 - 3*s2^2)^2)*(J2/3 + s2*sx + sy*sz - syz^2))/(J2 - 3*s2^2), s2/(3*(J2 - 3*s2^2)) - (2*sx)/(3*(J2 - 3*s2^2)) + sy/(3*(J2 - 3*s2^2)) - sy*(1/(3*(J2 - 3*s2^2)) - (J2/3 + s2*sz + sx*sy - sxy^2)/(J2 - 3*s2^2)^2) + ((sz/(J2 - 3*s2^2) + (6*s2*(J2/3 + s2*sz + sx*sy - sxy^2))/(J2 - 3*s2^2)^2)*(J2/3 + s2*sy + sx*sz - szx^2))/(J2 - 3*s2^2), sx/(3*(J2 - 3*s2^2)) - (2*s2)/(3*(J2 - 3*s2^2)) + sy/(3*(J2 - 3*s2^2)) - sz*(1/(3*(J2 - 3*s2^2)) - (J2/3 + s2*sz + sx*sy - sxy^2)/(J2 - 3*s2^2)^2) + ((sz/(J2 - 3*s2^2) + (6*s2*(J2/3 + s2*sz + sx*sy - sxy^2))/(J2 - 3*s2^2)^2)*(J2/3 + s2*sz + sx*sy - sxy^2))/(J2 - 3*s2^2), (2*sxy)/(J2 - 3*s2^2) - 2*sxy*(1/(3*(J2 - 3*s2^2)) - (J2/3 + s2*sz + sx*sy - sxy^2)/(J2 - 3*s2^2)^2) + ((sz/(J2 - 3*s2^2) + (6*s2*(J2/3 + s2*sz + sx*sy - sxy^2))/(J2 - 3*s2^2)^2)*(2*s2*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s2^2), ((sz/(J2 - 3*s2^2) + (6*s2*(J2/3 + s2*sz + sx*sy - sxy^2))/(J2 - 3*s2^2)^2)*(2*s2*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s2^2) - 2*syz*(1/(3*(J2 - 3*s2^2)) - (J2/3 + s2*sz + sx*sy - sxy^2)/(J2 - 3*s2^2)^2), ((sz/(J2 - 3*s2^2) + (6*s2*(J2/3 + s2*sz + sx*sy - sxy^2))/(J2 - 3*s2^2)^2)*(2*s2*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s2^2) - 2*szx*(1/(3*(J2 - 3*s2^2)) - (J2/3 + s2*sz + sx*sy - sxy^2)/(J2 - 3*s2^2)^2);
         (((2*sxy)/(J2 - 3*s2^2) + (6*s2*(2*s2*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s2^2)^2)*(J2/3 + s2*sx + sy*sz - syz^2))/(J2 - 3*s2^2) - (2*sxy)/(3*(J2 - 3*s2^2)) + (sx*(2*s2*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s2^2)^2, (((2*sxy)/(J2 - 3*s2^2) + (6*s2*(2*s2*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s2^2)^2)*(J2/3 + s2*sy + sx*sz - szx^2))/(J2 - 3*s2^2) - (2*sxy)/(3*(J2 - 3*s2^2)) + (sy*(2*s2*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s2^2)^2, (4*sxy)/(3*(J2 - 3*s2^2)) + (((2*sxy)/(J2 - 3*s2^2) + (6*s2*(2*s2*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s2^2)^2)*(J2/3 + s2*sz + sx*sy - sxy^2))/(J2 - 3*s2^2) + (sz*(2*s2*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s2^2)^2, (2*sxy*(2*s2*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s2^2)^2 - (2*s2 - 2*sz)/(J2 - 3*s2^2) + (((2*sxy)/(J2 - 3*s2^2) + (6*s2*(2*s2*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s2^2)^2)*(2*s2*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s2^2), (2*syz*(2*s2*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s2^2)^2 - (2*szx)/(J2 - 3*s2^2) + (((2*sxy)/(J2 - 3*s2^2) + (6*s2*(2*s2*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s2^2)^2)*(2*s2*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s2^2), (2*szx*(2*s2*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s2^2)^2 - (2*syz)/(J2 - 3*s2^2) + (((2*sxy)/(J2 - 3*s2^2) + (6*s2*(2*s2*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s2^2)^2)*(2*s2*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s2^2);
         (4*syz)/(3*(J2 - 3*s2^2)) + (((2*syz)/(J2 - 3*s2^2) + (6*s2*(2*s2*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s2^2)^2)*(J2/3 + s2*sx + sy*sz - syz^2))/(J2 - 3*s2^2) + (sx*(2*s2*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s2^2)^2, (((2*syz)/(J2 - 3*s2^2) + (6*s2*(2*s2*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s2^2)^2)*(J2/3 + s2*sy + sx*sz - szx^2))/(J2 - 3*s2^2) - (2*syz)/(3*(J2 - 3*s2^2)) + (sy*(2*s2*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s2^2)^2, (((2*syz)/(J2 - 3*s2^2) + (6*s2*(2*s2*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s2^2)^2)*(J2/3 + s2*sz + sx*sy - sxy^2))/(J2 - 3*s2^2) - (2*syz)/(3*(J2 - 3*s2^2)) + (sz*(2*s2*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s2^2)^2, (2*sxy*(2*s2*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s2^2)^2 - (2*szx)/(J2 - 3*s2^2) + (((2*syz)/(J2 - 3*s2^2) + (6*s2*(2*s2*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s2^2)^2)*(2*s2*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s2^2), (2*syz*(2*s2*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s2^2)^2 - (2*s2 - 2*sx)/(J2 - 3*s2^2) + (((2*syz)/(J2 - 3*s2^2) + (6*s2*(2*s2*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s2^2)^2)*(2*s2*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s2^2), (2*szx*(2*s2*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s2^2)^2 - (2*sxy)/(J2 - 3*s2^2) + (((2*syz)/(J2 - 3*s2^2) + (6*s2*(2*s2*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s2^2)^2)*(2*s2*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s2^2);
         (((2*szx)/(J2 - 3*s2^2) + (6*s2*(2*s2*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s2^2)^2)*(J2/3 + s2*sx + sy*sz - syz^2))/(J2 - 3*s2^2) - (2*szx)/(3*(J2 - 3*s2^2)) + (sx*(2*s2*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s2^2)^2, (4*szx)/(3*(J2 - 3*s2^2)) + (((2*szx)/(J2 - 3*s2^2) + (6*s2*(2*s2*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s2^2)^2)*(J2/3 + s2*sy + sx*sz - szx^2))/(J2 - 3*s2^2) + (sy*(2*s2*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s2^2)^2, (((2*szx)/(J2 - 3*s2^2) + (6*s2*(2*s2*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s2^2)^2)*(J2/3 + s2*sz + sx*sy - sxy^2))/(J2 - 3*s2^2) - (2*szx)/(3*(J2 - 3*s2^2)) + (sz*(2*s2*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s2^2)^2, (2*sxy*(2*s2*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s2^2)^2 - (2*syz)/(J2 - 3*s2^2) + (((2*szx)/(J2 - 3*s2^2) + (6*s2*(2*s2*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s2^2)^2)*(2*s2*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s2^2), (2*syz*(2*s2*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s2^2)^2 - (2*sxy)/(J2 - 3*s2^2) + (((2*szx)/(J2 - 3*s2^2) + (6*s2*(2*s2*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s2^2)^2)*(2*s2*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s2^2), (2*szx*(2*s2*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s2^2)^2 - (2*s2 - 2*sy)/(J2 - 3*s2^2) + (((2*szx)/(J2 - 3*s2^2) + (6*s2*(2*s2*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s2^2)^2)*(2*s2*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s2^2)];
ddXGddS2=[sy/(3*(J2 - 3*s3^2)) - (2*s3)/(3*(J2 - 3*s3^2)) + sz/(3*(J2 - 3*s3^2)) - sx*(1/(3*(J2 - 3*s3^2)) - (J2/3 + s3*sx + sy*sz - syz^2)/(J2 - 3*s3^2)^2) + ((sx/(J2 - 3*s3^2) + (6*s3*(J2/3 + s3*sx + sy*sz - syz^2))/(J2 - 3*s3^2)^2)*(J2/3 + s3*sx + sy*sz - syz^2))/(J2 - 3*s3^2), s3/(3*(J2 - 3*s3^2)) + sy/(3*(J2 - 3*s3^2)) - (2*sz)/(3*(J2 - 3*s3^2)) - sy*(1/(3*(J2 - 3*s3^2)) - (J2/3 + s3*sx + sy*sz - syz^2)/(J2 - 3*s3^2)^2) + ((sx/(J2 - 3*s3^2) + (6*s3*(J2/3 + s3*sx + sy*sz - syz^2))/(J2 - 3*s3^2)^2)*(J2/3 + s3*sy + sx*sz - szx^2))/(J2 - 3*s3^2), s3/(3*(J2 - 3*s3^2)) - (2*sy)/(3*(J2 - 3*s3^2)) + sz/(3*(J2 - 3*s3^2)) - sz*(1/(3*(J2 - 3*s3^2)) - (J2/3 + s3*sx + sy*sz - syz^2)/(J2 - 3*s3^2)^2) + ((sx/(J2 - 3*s3^2) + (6*s3*(J2/3 + s3*sx + sy*sz - syz^2))/(J2 - 3*s3^2)^2)*(J2/3 + s3*sz + sx*sy - sxy^2))/(J2 - 3*s3^2), ((sx/(J2 - 3*s3^2) + (6*s3*(J2/3 + s3*sx + sy*sz - syz^2))/(J2 - 3*s3^2)^2)*(2*s3*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s3^2) - 2*sxy*(1/(3*(J2 - 3*s3^2)) - (J2/3 + s3*sx + sy*sz - syz^2)/(J2 - 3*s3^2)^2), (2*syz)/(J2 - 3*s3^2) - 2*syz*(1/(3*(J2 - 3*s3^2)) - (J2/3 + s3*sx + sy*sz - syz^2)/(J2 - 3*s3^2)^2) + ((sx/(J2 - 3*s3^2) + (6*s3*(J2/3 + s3*sx + sy*sz - syz^2))/(J2 - 3*s3^2)^2)*(2*s3*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s3^2), ((sx/(J2 - 3*s3^2) + (6*s3*(J2/3 + s3*sx + sy*sz - syz^2))/(J2 - 3*s3^2)^2)*(2*s3*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s3^2) - 2*szx*(1/(3*(J2 - 3*s3^2)) - (J2/3 + s3*sx + sy*sz - syz^2)/(J2 - 3*s3^2)^2);
         s3/(3*(J2 - 3*s3^2)) + sx/(3*(J2 - 3*s3^2)) - (2*sz)/(3*(J2 - 3*s3^2)) - sx*(1/(3*(J2 - 3*s3^2)) - (J2/3 + s3*sy + sx*sz - szx^2)/(J2 - 3*s3^2)^2) + ((sy/(J2 - 3*s3^2) + (6*s3*(J2/3 + s3*sy + sx*sz - szx^2))/(J2 - 3*s3^2)^2)*(J2/3 + s3*sx + sy*sz - syz^2))/(J2 - 3*s3^2), sx/(3*(J2 - 3*s3^2)) - (2*s3)/(3*(J2 - 3*s3^2)) + sz/(3*(J2 - 3*s3^2)) - sy*(1/(3*(J2 - 3*s3^2)) - (J2/3 + s3*sy + sx*sz - szx^2)/(J2 - 3*s3^2)^2) + ((sy/(J2 - 3*s3^2) + (6*s3*(J2/3 + s3*sy + sx*sz - szx^2))/(J2 - 3*s3^2)^2)*(J2/3 + s3*sy + sx*sz - szx^2))/(J2 - 3*s3^2), s3/(3*(J2 - 3*s3^2)) - (2*sx)/(3*(J2 - 3*s3^2)) + sz/(3*(J2 - 3*s3^2)) - sz*(1/(3*(J2 - 3*s3^2)) - (J2/3 + s3*sy + sx*sz - szx^2)/(J2 - 3*s3^2)^2) + ((sy/(J2 - 3*s3^2) + (6*s3*(J2/3 + s3*sy + sx*sz - szx^2))/(J2 - 3*s3^2)^2)*(J2/3 + s3*sz + sx*sy - sxy^2))/(J2 - 3*s3^2), ((sy/(J2 - 3*s3^2) + (6*s3*(J2/3 + s3*sy + sx*sz - szx^2))/(J2 - 3*s3^2)^2)*(2*s3*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s3^2) - 2*sxy*(1/(3*(J2 - 3*s3^2)) - (J2/3 + s3*sy + sx*sz - szx^2)/(J2 - 3*s3^2)^2), ((sy/(J2 - 3*s3^2) + (6*s3*(J2/3 + s3*sy + sx*sz - szx^2))/(J2 - 3*s3^2)^2)*(2*s3*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s3^2) - 2*syz*(1/(3*(J2 - 3*s3^2)) - (J2/3 + s3*sy + sx*sz - szx^2)/(J2 - 3*s3^2)^2), (2*szx)/(J2 - 3*s3^2) - 2*szx*(1/(3*(J2 - 3*s3^2)) - (J2/3 + s3*sy + sx*sz - szx^2)/(J2 - 3*s3^2)^2) + ((sy/(J2 - 3*s3^2) + (6*s3*(J2/3 + s3*sy + sx*sz - szx^2))/(J2 - 3*s3^2)^2)*(2*s3*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s3^2);
         s3/(3*(J2 - 3*s3^2)) + sx/(3*(J2 - 3*s3^2)) - (2*sy)/(3*(J2 - 3*s3^2)) - sx*(1/(3*(J2 - 3*s3^2)) - (J2/3 + s3*sz + sx*sy - sxy^2)/(J2 - 3*s3^2)^2) + ((sz/(J2 - 3*s3^2) + (6*s3*(J2/3 + s3*sz + sx*sy - sxy^2))/(J2 - 3*s3^2)^2)*(J2/3 + s3*sx + sy*sz - syz^2))/(J2 - 3*s3^2), s3/(3*(J2 - 3*s3^2)) - (2*sx)/(3*(J2 - 3*s3^2)) + sy/(3*(J2 - 3*s3^2)) - sy*(1/(3*(J2 - 3*s3^2)) - (J2/3 + s3*sz + sx*sy - sxy^2)/(J2 - 3*s3^2)^2) + ((sz/(J2 - 3*s3^2) + (6*s3*(J2/3 + s3*sz + sx*sy - sxy^2))/(J2 - 3*s3^2)^2)*(J2/3 + s3*sy + sx*sz - szx^2))/(J2 - 3*s3^2), sx/(3*(J2 - 3*s3^2)) - (2*s3)/(3*(J2 - 3*s3^2)) + sy/(3*(J2 - 3*s3^2)) - sz*(1/(3*(J2 - 3*s3^2)) - (J2/3 + s3*sz + sx*sy - sxy^2)/(J2 - 3*s3^2)^2) + ((sz/(J2 - 3*s3^2) + (6*s3*(J2/3 + s3*sz + sx*sy - sxy^2))/(J2 - 3*s3^2)^2)*(J2/3 + s3*sz + sx*sy - sxy^2))/(J2 - 3*s3^2), (2*sxy)/(J2 - 3*s3^2) - 2*sxy*(1/(3*(J2 - 3*s3^2)) - (J2/3 + s3*sz + sx*sy - sxy^2)/(J2 - 3*s3^2)^2) + ((sz/(J2 - 3*s3^2) + (6*s3*(J2/3 + s3*sz + sx*sy - sxy^2))/(J2 - 3*s3^2)^2)*(2*s3*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s3^2), ((sz/(J2 - 3*s3^2) + (6*s3*(J2/3 + s3*sz + sx*sy - sxy^2))/(J2 - 3*s3^2)^2)*(2*s3*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s3^2) - 2*syz*(1/(3*(J2 - 3*s3^2)) - (J2/3 + s3*sz + sx*sy - sxy^2)/(J2 - 3*s3^2)^2), ((sz/(J2 - 3*s3^2) + (6*s3*(J2/3 + s3*sz + sx*sy - sxy^2))/(J2 - 3*s3^2)^2)*(2*s3*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s3^2) - 2*szx*(1/(3*(J2 - 3*s3^2)) - (J2/3 + s3*sz + sx*sy - sxy^2)/(J2 - 3*s3^2)^2);
         (((2*sxy)/(J2 - 3*s3^2) + (6*s3*(2*s3*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s3^2)^2)*(J2/3 + s3*sx + sy*sz - syz^2))/(J2 - 3*s3^2) - (2*sxy)/(3*(J2 - 3*s3^2)) + (sx*(2*s3*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s3^2)^2, (((2*sxy)/(J2 - 3*s3^2) + (6*s3*(2*s3*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s3^2)^2)*(J2/3 + s3*sy + sx*sz - szx^2))/(J2 - 3*s3^2) - (2*sxy)/(3*(J2 - 3*s3^2)) + (sy*(2*s3*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s3^2)^2, (4*sxy)/(3*(J2 - 3*s3^2)) + (((2*sxy)/(J2 - 3*s3^2) + (6*s3*(2*s3*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s3^2)^2)*(J2/3 + s3*sz + sx*sy - sxy^2))/(J2 - 3*s3^2) + (sz*(2*s3*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s3^2)^2, (2*sxy*(2*s3*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s3^2)^2 - (2*s3 - 2*sz)/(J2 - 3*s3^2) + (((2*sxy)/(J2 - 3*s3^2) + (6*s3*(2*s3*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s3^2)^2)*(2*s3*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s3^2), (2*syz*(2*s3*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s3^2)^2 - (2*szx)/(J2 - 3*s3^2) + (((2*sxy)/(J2 - 3*s3^2) + (6*s3*(2*s3*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s3^2)^2)*(2*s3*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s3^2), (2*szx*(2*s3*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s3^2)^2 - (2*syz)/(J2 - 3*s3^2) + (((2*sxy)/(J2 - 3*s3^2) + (6*s3*(2*s3*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s3^2)^2)*(2*s3*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s3^2);
         (4*syz)/(3*(J2 - 3*s3^2)) + (((2*syz)/(J2 - 3*s3^2) + (6*s3*(2*s3*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s3^2)^2)*(J2/3 + s3*sx + sy*sz - syz^2))/(J2 - 3*s3^2) + (sx*(2*s3*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s3^2)^2, (((2*syz)/(J2 - 3*s3^2) + (6*s3*(2*s3*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s3^2)^2)*(J2/3 + s3*sy + sx*sz - szx^2))/(J2 - 3*s3^2) - (2*syz)/(3*(J2 - 3*s3^2)) + (sy*(2*s3*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s3^2)^2, (((2*syz)/(J2 - 3*s3^2) + (6*s3*(2*s3*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s3^2)^2)*(J2/3 + s3*sz + sx*sy - sxy^2))/(J2 - 3*s3^2) - (2*syz)/(3*(J2 - 3*s3^2)) + (sz*(2*s3*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s3^2)^2, (2*sxy*(2*s3*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s3^2)^2 - (2*szx)/(J2 - 3*s3^2) + (((2*syz)/(J2 - 3*s3^2) + (6*s3*(2*s3*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s3^2)^2)*(2*s3*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s3^2), (2*syz*(2*s3*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s3^2)^2 - (2*s3 - 2*sx)/(J2 - 3*s3^2) + (((2*syz)/(J2 - 3*s3^2) + (6*s3*(2*s3*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s3^2)^2)*(2*s3*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s3^2), (2*szx*(2*s3*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s3^2)^2 - (2*sxy)/(J2 - 3*s3^2) + (((2*syz)/(J2 - 3*s3^2) + (6*s3*(2*s3*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s3^2)^2)*(2*s3*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s3^2);
         (((2*szx)/(J2 - 3*s3^2) + (6*s3*(2*s3*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s3^2)^2)*(J2/3 + s3*sx + sy*sz - syz^2))/(J2 - 3*s3^2) - (2*szx)/(3*(J2 - 3*s3^2)) + (sx*(2*s3*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s3^2)^2, (4*szx)/(3*(J2 - 3*s3^2)) + (((2*szx)/(J2 - 3*s3^2) + (6*s3*(2*s3*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s3^2)^2)*(J2/3 + s3*sy + sx*sz - szx^2))/(J2 - 3*s3^2) + (sy*(2*s3*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s3^2)^2, (((2*szx)/(J2 - 3*s3^2) + (6*s3*(2*s3*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s3^2)^2)*(J2/3 + s3*sz + sx*sy - sxy^2))/(J2 - 3*s3^2) - (2*szx)/(3*(J2 - 3*s3^2)) + (sz*(2*s3*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s3^2)^2, (2*sxy*(2*s3*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s3^2)^2 - (2*syz)/(J2 - 3*s3^2) + (((2*szx)/(J2 - 3*s3^2) + (6*s3*(2*s3*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s3^2)^2)*(2*s3*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s3^2), (2*syz*(2*s3*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s3^2)^2 - (2*sxy)/(J2 - 3*s3^2) + (((2*szx)/(J2 - 3*s3^2) + (6*s3*(2*s3*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s3^2)^2)*(2*s3*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s3^2), (2*szx*(2*s3*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s3^2)^2 - (2*s3 - 2*sy)/(J2 - 3*s3^2) + (((2*szx)/(J2 - 3*s3^2) + (6*s3*(2*s3*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s3^2)^2)*(2*s3*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s3^2)];
ddGddS=dXGdS*ddGddX*dXGdS.'+ddXGddS1*dGdX(1)+ddXGddS2*dGdX(2);
end

function [dGdS,ddGddS]=calculate_dG3dS(J2, s1, s2, sx, sxy, sy, syz, sz, szx)
dXGdS=[-(J2/3 + s1*sx + sy*sz - syz^2)/(J2 - 3*s1^2), -(J2/3 + s2*sx + sy*sz - syz^2)/(J2 - 3*s2^2);
       -(J2/3 + s1*sy + sx*sz - szx^2)/(J2 - 3*s1^2), -(J2/3 + s2*sy + sx*sz - szx^2)/(J2 - 3*s2^2);
       -(J2/3 + s1*sz + sx*sy - sxy^2)/(J2 - 3*s1^2), -(J2/3 + s2*sz + sx*sy - sxy^2)/(J2 - 3*s2^2);
       -(2*s1*sxy - 2*sxy*sz + 2*syz*szx)/(J2 - 3*s1^2), -(2*s2*sxy - 2*sxy*sz + 2*syz*szx)/(J2 - 3*s2^2);
       -(2*s1*syz - 2*sx*syz + 2*sxy*szx)/(J2 - 3*s1^2), -(2*s2*syz - 2*sx*syz + 2*sxy*szx)/(J2 - 3*s2^2);
       -(2*s1*szx + 2*sxy*syz - 2*sy*szx)/(J2 - 3*s1^2), -(2*s2*szx + 2*sxy*syz - 2*sy*szx)/(J2 - 3*s2^2)];
dGdX=[1;
      -1];
dGdS=dXGdS*dGdX;

ddGddX=[0, 0;
        0, 0];
ddXGddS1=[sy/(3*(J2 - 3*s1^2)) - (2*s1)/(3*(J2 - 3*s1^2)) + sz/(3*(J2 - 3*s1^2)) - sx*(1/(3*(J2 - 3*s1^2)) - (J2/3 + s1*sx + sy*sz - syz^2)/(J2 - 3*s1^2)^2) + ((sx/(J2 - 3*s1^2) + (6*s1*(J2/3 + s1*sx + sy*sz - syz^2))/(J2 - 3*s1^2)^2)*(J2/3 + s1*sx + sy*sz - syz^2))/(J2 - 3*s1^2), s1/(3*(J2 - 3*s1^2)) + sy/(3*(J2 - 3*s1^2)) - (2*sz)/(3*(J2 - 3*s1^2)) - sy*(1/(3*(J2 - 3*s1^2)) - (J2/3 + s1*sx + sy*sz - syz^2)/(J2 - 3*s1^2)^2) + ((sx/(J2 - 3*s1^2) + (6*s1*(J2/3 + s1*sx + sy*sz - syz^2))/(J2 - 3*s1^2)^2)*(J2/3 + s1*sy + sx*sz - szx^2))/(J2 - 3*s1^2), s1/(3*(J2 - 3*s1^2)) - (2*sy)/(3*(J2 - 3*s1^2)) + sz/(3*(J2 - 3*s1^2)) - sz*(1/(3*(J2 - 3*s1^2)) - (J2/3 + s1*sx + sy*sz - syz^2)/(J2 - 3*s1^2)^2) + ((sx/(J2 - 3*s1^2) + (6*s1*(J2/3 + s1*sx + sy*sz - syz^2))/(J2 - 3*s1^2)^2)*(J2/3 + s1*sz + sx*sy - sxy^2))/(J2 - 3*s1^2), ((sx/(J2 - 3*s1^2) + (6*s1*(J2/3 + s1*sx + sy*sz - syz^2))/(J2 - 3*s1^2)^2)*(2*s1*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s1^2) - 2*sxy*(1/(3*(J2 - 3*s1^2)) - (J2/3 + s1*sx + sy*sz - syz^2)/(J2 - 3*s1^2)^2), (2*syz)/(J2 - 3*s1^2) - 2*syz*(1/(3*(J2 - 3*s1^2)) - (J2/3 + s1*sx + sy*sz - syz^2)/(J2 - 3*s1^2)^2) + ((sx/(J2 - 3*s1^2) + (6*s1*(J2/3 + s1*sx + sy*sz - syz^2))/(J2 - 3*s1^2)^2)*(2*s1*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s1^2), ((sx/(J2 - 3*s1^2) + (6*s1*(J2/3 + s1*sx + sy*sz - syz^2))/(J2 - 3*s1^2)^2)*(2*s1*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s1^2) - 2*szx*(1/(3*(J2 - 3*s1^2)) - (J2/3 + s1*sx + sy*sz - syz^2)/(J2 - 3*s1^2)^2);
         s1/(3*(J2 - 3*s1^2)) + sx/(3*(J2 - 3*s1^2)) - (2*sz)/(3*(J2 - 3*s1^2)) - sx*(1/(3*(J2 - 3*s1^2)) - (J2/3 + s1*sy + sx*sz - szx^2)/(J2 - 3*s1^2)^2) + ((sy/(J2 - 3*s1^2) + (6*s1*(J2/3 + s1*sy + sx*sz - szx^2))/(J2 - 3*s1^2)^2)*(J2/3 + s1*sx + sy*sz - syz^2))/(J2 - 3*s1^2), sx/(3*(J2 - 3*s1^2)) - (2*s1)/(3*(J2 - 3*s1^2)) + sz/(3*(J2 - 3*s1^2)) - sy*(1/(3*(J2 - 3*s1^2)) - (J2/3 + s1*sy + sx*sz - szx^2)/(J2 - 3*s1^2)^2) + ((sy/(J2 - 3*s1^2) + (6*s1*(J2/3 + s1*sy + sx*sz - szx^2))/(J2 - 3*s1^2)^2)*(J2/3 + s1*sy + sx*sz - szx^2))/(J2 - 3*s1^2), s1/(3*(J2 - 3*s1^2)) - (2*sx)/(3*(J2 - 3*s1^2)) + sz/(3*(J2 - 3*s1^2)) - sz*(1/(3*(J2 - 3*s1^2)) - (J2/3 + s1*sy + sx*sz - szx^2)/(J2 - 3*s1^2)^2) + ((sy/(J2 - 3*s1^2) + (6*s1*(J2/3 + s1*sy + sx*sz - szx^2))/(J2 - 3*s1^2)^2)*(J2/3 + s1*sz + sx*sy - sxy^2))/(J2 - 3*s1^2), ((sy/(J2 - 3*s1^2) + (6*s1*(J2/3 + s1*sy + sx*sz - szx^2))/(J2 - 3*s1^2)^2)*(2*s1*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s1^2) - 2*sxy*(1/(3*(J2 - 3*s1^2)) - (J2/3 + s1*sy + sx*sz - szx^2)/(J2 - 3*s1^2)^2), ((sy/(J2 - 3*s1^2) + (6*s1*(J2/3 + s1*sy + sx*sz - szx^2))/(J2 - 3*s1^2)^2)*(2*s1*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s1^2) - 2*syz*(1/(3*(J2 - 3*s1^2)) - (J2/3 + s1*sy + sx*sz - szx^2)/(J2 - 3*s1^2)^2), (2*szx)/(J2 - 3*s1^2) - 2*szx*(1/(3*(J2 - 3*s1^2)) - (J2/3 + s1*sy + sx*sz - szx^2)/(J2 - 3*s1^2)^2) + ((sy/(J2 - 3*s1^2) + (6*s1*(J2/3 + s1*sy + sx*sz - szx^2))/(J2 - 3*s1^2)^2)*(2*s1*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s1^2);
         s1/(3*(J2 - 3*s1^2)) + sx/(3*(J2 - 3*s1^2)) - (2*sy)/(3*(J2 - 3*s1^2)) - sx*(1/(3*(J2 - 3*s1^2)) - (J2/3 + s1*sz + sx*sy - sxy^2)/(J2 - 3*s1^2)^2) + ((sz/(J2 - 3*s1^2) + (6*s1*(J2/3 + s1*sz + sx*sy - sxy^2))/(J2 - 3*s1^2)^2)*(J2/3 + s1*sx + sy*sz - syz^2))/(J2 - 3*s1^2), s1/(3*(J2 - 3*s1^2)) - (2*sx)/(3*(J2 - 3*s1^2)) + sy/(3*(J2 - 3*s1^2)) - sy*(1/(3*(J2 - 3*s1^2)) - (J2/3 + s1*sz + sx*sy - sxy^2)/(J2 - 3*s1^2)^2) + ((sz/(J2 - 3*s1^2) + (6*s1*(J2/3 + s1*sz + sx*sy - sxy^2))/(J2 - 3*s1^2)^2)*(J2/3 + s1*sy + sx*sz - szx^2))/(J2 - 3*s1^2), sx/(3*(J2 - 3*s1^2)) - (2*s1)/(3*(J2 - 3*s1^2)) + sy/(3*(J2 - 3*s1^2)) - sz*(1/(3*(J2 - 3*s1^2)) - (J2/3 + s1*sz + sx*sy - sxy^2)/(J2 - 3*s1^2)^2) + ((sz/(J2 - 3*s1^2) + (6*s1*(J2/3 + s1*sz + sx*sy - sxy^2))/(J2 - 3*s1^2)^2)*(J2/3 + s1*sz + sx*sy - sxy^2))/(J2 - 3*s1^2), (2*sxy)/(J2 - 3*s1^2) - 2*sxy*(1/(3*(J2 - 3*s1^2)) - (J2/3 + s1*sz + sx*sy - sxy^2)/(J2 - 3*s1^2)^2) + ((sz/(J2 - 3*s1^2) + (6*s1*(J2/3 + s1*sz + sx*sy - sxy^2))/(J2 - 3*s1^2)^2)*(2*s1*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s1^2), ((sz/(J2 - 3*s1^2) + (6*s1*(J2/3 + s1*sz + sx*sy - sxy^2))/(J2 - 3*s1^2)^2)*(2*s1*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s1^2) - 2*syz*(1/(3*(J2 - 3*s1^2)) - (J2/3 + s1*sz + sx*sy - sxy^2)/(J2 - 3*s1^2)^2), ((sz/(J2 - 3*s1^2) + (6*s1*(J2/3 + s1*sz + sx*sy - sxy^2))/(J2 - 3*s1^2)^2)*(2*s1*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s1^2) - 2*szx*(1/(3*(J2 - 3*s1^2)) - (J2/3 + s1*sz + sx*sy - sxy^2)/(J2 - 3*s1^2)^2);
         (((2*sxy)/(J2 - 3*s1^2) + (6*s1*(2*s1*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s1^2)^2)*(J2/3 + s1*sx + sy*sz - syz^2))/(J2 - 3*s1^2) - (2*sxy)/(3*(J2 - 3*s1^2)) + (sx*(2*s1*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s1^2)^2, (((2*sxy)/(J2 - 3*s1^2) + (6*s1*(2*s1*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s1^2)^2)*(J2/3 + s1*sy + sx*sz - szx^2))/(J2 - 3*s1^2) - (2*sxy)/(3*(J2 - 3*s1^2)) + (sy*(2*s1*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s1^2)^2, (4*sxy)/(3*(J2 - 3*s1^2)) + (((2*sxy)/(J2 - 3*s1^2) + (6*s1*(2*s1*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s1^2)^2)*(J2/3 + s1*sz + sx*sy - sxy^2))/(J2 - 3*s1^2) + (sz*(2*s1*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s1^2)^2, (2*sxy*(2*s1*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s1^2)^2 - (2*s1 - 2*sz)/(J2 - 3*s1^2) + (((2*sxy)/(J2 - 3*s1^2) + (6*s1*(2*s1*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s1^2)^2)*(2*s1*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s1^2), (2*syz*(2*s1*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s1^2)^2 - (2*szx)/(J2 - 3*s1^2) + (((2*sxy)/(J2 - 3*s1^2) + (6*s1*(2*s1*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s1^2)^2)*(2*s1*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s1^2), (2*szx*(2*s1*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s1^2)^2 - (2*syz)/(J2 - 3*s1^2) + (((2*sxy)/(J2 - 3*s1^2) + (6*s1*(2*s1*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s1^2)^2)*(2*s1*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s1^2);
         (4*syz)/(3*(J2 - 3*s1^2)) + (((2*syz)/(J2 - 3*s1^2) + (6*s1*(2*s1*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s1^2)^2)*(J2/3 + s1*sx + sy*sz - syz^2))/(J2 - 3*s1^2) + (sx*(2*s1*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s1^2)^2, (((2*syz)/(J2 - 3*s1^2) + (6*s1*(2*s1*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s1^2)^2)*(J2/3 + s1*sy + sx*sz - szx^2))/(J2 - 3*s1^2) - (2*syz)/(3*(J2 - 3*s1^2)) + (sy*(2*s1*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s1^2)^2, (((2*syz)/(J2 - 3*s1^2) + (6*s1*(2*s1*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s1^2)^2)*(J2/3 + s1*sz + sx*sy - sxy^2))/(J2 - 3*s1^2) - (2*syz)/(3*(J2 - 3*s1^2)) + (sz*(2*s1*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s1^2)^2, (2*sxy*(2*s1*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s1^2)^2 - (2*szx)/(J2 - 3*s1^2) + (((2*syz)/(J2 - 3*s1^2) + (6*s1*(2*s1*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s1^2)^2)*(2*s1*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s1^2), (2*syz*(2*s1*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s1^2)^2 - (2*s1 - 2*sx)/(J2 - 3*s1^2) + (((2*syz)/(J2 - 3*s1^2) + (6*s1*(2*s1*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s1^2)^2)*(2*s1*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s1^2), (2*szx*(2*s1*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s1^2)^2 - (2*sxy)/(J2 - 3*s1^2) + (((2*syz)/(J2 - 3*s1^2) + (6*s1*(2*s1*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s1^2)^2)*(2*s1*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s1^2);
         (((2*szx)/(J2 - 3*s1^2) + (6*s1*(2*s1*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s1^2)^2)*(J2/3 + s1*sx + sy*sz - syz^2))/(J2 - 3*s1^2) - (2*szx)/(3*(J2 - 3*s1^2)) + (sx*(2*s1*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s1^2)^2, (4*szx)/(3*(J2 - 3*s1^2)) + (((2*szx)/(J2 - 3*s1^2) + (6*s1*(2*s1*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s1^2)^2)*(J2/3 + s1*sy + sx*sz - szx^2))/(J2 - 3*s1^2) + (sy*(2*s1*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s1^2)^2, (((2*szx)/(J2 - 3*s1^2) + (6*s1*(2*s1*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s1^2)^2)*(J2/3 + s1*sz + sx*sy - sxy^2))/(J2 - 3*s1^2) - (2*szx)/(3*(J2 - 3*s1^2)) + (sz*(2*s1*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s1^2)^2, (2*sxy*(2*s1*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s1^2)^2 - (2*syz)/(J2 - 3*s1^2) + (((2*szx)/(J2 - 3*s1^2) + (6*s1*(2*s1*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s1^2)^2)*(2*s1*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s1^2), (2*syz*(2*s1*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s1^2)^2 - (2*sxy)/(J2 - 3*s1^2) + (((2*szx)/(J2 - 3*s1^2) + (6*s1*(2*s1*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s1^2)^2)*(2*s1*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s1^2), (2*szx*(2*s1*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s1^2)^2 - (2*s1 - 2*sy)/(J2 - 3*s1^2) + (((2*szx)/(J2 - 3*s1^2) + (6*s1*(2*s1*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s1^2)^2)*(2*s1*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s1^2)];
ddXGddS2=[sy/(3*(J2 - 3*s2^2)) - (2*s2)/(3*(J2 - 3*s2^2)) + sz/(3*(J2 - 3*s2^2)) - sx*(1/(3*(J2 - 3*s2^2)) - (J2/3 + s2*sx + sy*sz - syz^2)/(J2 - 3*s2^2)^2) + ((sx/(J2 - 3*s2^2) + (6*s2*(J2/3 + s2*sx + sy*sz - syz^2))/(J2 - 3*s2^2)^2)*(J2/3 + s2*sx + sy*sz - syz^2))/(J2 - 3*s2^2), s2/(3*(J2 - 3*s2^2)) + sy/(3*(J2 - 3*s2^2)) - (2*sz)/(3*(J2 - 3*s2^2)) - sy*(1/(3*(J2 - 3*s2^2)) - (J2/3 + s2*sx + sy*sz - syz^2)/(J2 - 3*s2^2)^2) + ((sx/(J2 - 3*s2^2) + (6*s2*(J2/3 + s2*sx + sy*sz - syz^2))/(J2 - 3*s2^2)^2)*(J2/3 + s2*sy + sx*sz - szx^2))/(J2 - 3*s2^2), s2/(3*(J2 - 3*s2^2)) - (2*sy)/(3*(J2 - 3*s2^2)) + sz/(3*(J2 - 3*s2^2)) - sz*(1/(3*(J2 - 3*s2^2)) - (J2/3 + s2*sx + sy*sz - syz^2)/(J2 - 3*s2^2)^2) + ((sx/(J2 - 3*s2^2) + (6*s2*(J2/3 + s2*sx + sy*sz - syz^2))/(J2 - 3*s2^2)^2)*(J2/3 + s2*sz + sx*sy - sxy^2))/(J2 - 3*s2^2), ((sx/(J2 - 3*s2^2) + (6*s2*(J2/3 + s2*sx + sy*sz - syz^2))/(J2 - 3*s2^2)^2)*(2*s2*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s2^2) - 2*sxy*(1/(3*(J2 - 3*s2^2)) - (J2/3 + s2*sx + sy*sz - syz^2)/(J2 - 3*s2^2)^2), (2*syz)/(J2 - 3*s2^2) - 2*syz*(1/(3*(J2 - 3*s2^2)) - (J2/3 + s2*sx + sy*sz - syz^2)/(J2 - 3*s2^2)^2) + ((sx/(J2 - 3*s2^2) + (6*s2*(J2/3 + s2*sx + sy*sz - syz^2))/(J2 - 3*s2^2)^2)*(2*s2*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s2^2), ((sx/(J2 - 3*s2^2) + (6*s2*(J2/3 + s2*sx + sy*sz - syz^2))/(J2 - 3*s2^2)^2)*(2*s2*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s2^2) - 2*szx*(1/(3*(J2 - 3*s2^2)) - (J2/3 + s2*sx + sy*sz - syz^2)/(J2 - 3*s2^2)^2);
         s2/(3*(J2 - 3*s2^2)) + sx/(3*(J2 - 3*s2^2)) - (2*sz)/(3*(J2 - 3*s2^2)) - sx*(1/(3*(J2 - 3*s2^2)) - (J2/3 + s2*sy + sx*sz - szx^2)/(J2 - 3*s2^2)^2) + ((sy/(J2 - 3*s2^2) + (6*s2*(J2/3 + s2*sy + sx*sz - szx^2))/(J2 - 3*s2^2)^2)*(J2/3 + s2*sx + sy*sz - syz^2))/(J2 - 3*s2^2), sx/(3*(J2 - 3*s2^2)) - (2*s2)/(3*(J2 - 3*s2^2)) + sz/(3*(J2 - 3*s2^2)) - sy*(1/(3*(J2 - 3*s2^2)) - (J2/3 + s2*sy + sx*sz - szx^2)/(J2 - 3*s2^2)^2) + ((sy/(J2 - 3*s2^2) + (6*s2*(J2/3 + s2*sy + sx*sz - szx^2))/(J2 - 3*s2^2)^2)*(J2/3 + s2*sy + sx*sz - szx^2))/(J2 - 3*s2^2), s2/(3*(J2 - 3*s2^2)) - (2*sx)/(3*(J2 - 3*s2^2)) + sz/(3*(J2 - 3*s2^2)) - sz*(1/(3*(J2 - 3*s2^2)) - (J2/3 + s2*sy + sx*sz - szx^2)/(J2 - 3*s2^2)^2) + ((sy/(J2 - 3*s2^2) + (6*s2*(J2/3 + s2*sy + sx*sz - szx^2))/(J2 - 3*s2^2)^2)*(J2/3 + s2*sz + sx*sy - sxy^2))/(J2 - 3*s2^2), ((sy/(J2 - 3*s2^2) + (6*s2*(J2/3 + s2*sy + sx*sz - szx^2))/(J2 - 3*s2^2)^2)*(2*s2*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s2^2) - 2*sxy*(1/(3*(J2 - 3*s2^2)) - (J2/3 + s2*sy + sx*sz - szx^2)/(J2 - 3*s2^2)^2), ((sy/(J2 - 3*s2^2) + (6*s2*(J2/3 + s2*sy + sx*sz - szx^2))/(J2 - 3*s2^2)^2)*(2*s2*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s2^2) - 2*syz*(1/(3*(J2 - 3*s2^2)) - (J2/3 + s2*sy + sx*sz - szx^2)/(J2 - 3*s2^2)^2), (2*szx)/(J2 - 3*s2^2) - 2*szx*(1/(3*(J2 - 3*s2^2)) - (J2/3 + s2*sy + sx*sz - szx^2)/(J2 - 3*s2^2)^2) + ((sy/(J2 - 3*s2^2) + (6*s2*(J2/3 + s2*sy + sx*sz - szx^2))/(J2 - 3*s2^2)^2)*(2*s2*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s2^2);
         s2/(3*(J2 - 3*s2^2)) + sx/(3*(J2 - 3*s2^2)) - (2*sy)/(3*(J2 - 3*s2^2)) - sx*(1/(3*(J2 - 3*s2^2)) - (J2/3 + s2*sz + sx*sy - sxy^2)/(J2 - 3*s2^2)^2) + ((sz/(J2 - 3*s2^2) + (6*s2*(J2/3 + s2*sz + sx*sy - sxy^2))/(J2 - 3*s2^2)^2)*(J2/3 + s2*sx + sy*sz - syz^2))/(J2 - 3*s2^2), s2/(3*(J2 - 3*s2^2)) - (2*sx)/(3*(J2 - 3*s2^2)) + sy/(3*(J2 - 3*s2^2)) - sy*(1/(3*(J2 - 3*s2^2)) - (J2/3 + s2*sz + sx*sy - sxy^2)/(J2 - 3*s2^2)^2) + ((sz/(J2 - 3*s2^2) + (6*s2*(J2/3 + s2*sz + sx*sy - sxy^2))/(J2 - 3*s2^2)^2)*(J2/3 + s2*sy + sx*sz - szx^2))/(J2 - 3*s2^2), sx/(3*(J2 - 3*s2^2)) - (2*s2)/(3*(J2 - 3*s2^2)) + sy/(3*(J2 - 3*s2^2)) - sz*(1/(3*(J2 - 3*s2^2)) - (J2/3 + s2*sz + sx*sy - sxy^2)/(J2 - 3*s2^2)^2) + ((sz/(J2 - 3*s2^2) + (6*s2*(J2/3 + s2*sz + sx*sy - sxy^2))/(J2 - 3*s2^2)^2)*(J2/3 + s2*sz + sx*sy - sxy^2))/(J2 - 3*s2^2), (2*sxy)/(J2 - 3*s2^2) - 2*sxy*(1/(3*(J2 - 3*s2^2)) - (J2/3 + s2*sz + sx*sy - sxy^2)/(J2 - 3*s2^2)^2) + ((sz/(J2 - 3*s2^2) + (6*s2*(J2/3 + s2*sz + sx*sy - sxy^2))/(J2 - 3*s2^2)^2)*(2*s2*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s2^2), ((sz/(J2 - 3*s2^2) + (6*s2*(J2/3 + s2*sz + sx*sy - sxy^2))/(J2 - 3*s2^2)^2)*(2*s2*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s2^2) - 2*syz*(1/(3*(J2 - 3*s2^2)) - (J2/3 + s2*sz + sx*sy - sxy^2)/(J2 - 3*s2^2)^2), ((sz/(J2 - 3*s2^2) + (6*s2*(J2/3 + s2*sz + sx*sy - sxy^2))/(J2 - 3*s2^2)^2)*(2*s2*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s2^2) - 2*szx*(1/(3*(J2 - 3*s2^2)) - (J2/3 + s2*sz + sx*sy - sxy^2)/(J2 - 3*s2^2)^2);
         (((2*sxy)/(J2 - 3*s2^2) + (6*s2*(2*s2*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s2^2)^2)*(J2/3 + s2*sx + sy*sz - syz^2))/(J2 - 3*s2^2) - (2*sxy)/(3*(J2 - 3*s2^2)) + (sx*(2*s2*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s2^2)^2, (((2*sxy)/(J2 - 3*s2^2) + (6*s2*(2*s2*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s2^2)^2)*(J2/3 + s2*sy + sx*sz - szx^2))/(J2 - 3*s2^2) - (2*sxy)/(3*(J2 - 3*s2^2)) + (sy*(2*s2*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s2^2)^2, (4*sxy)/(3*(J2 - 3*s2^2)) + (((2*sxy)/(J2 - 3*s2^2) + (6*s2*(2*s2*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s2^2)^2)*(J2/3 + s2*sz + sx*sy - sxy^2))/(J2 - 3*s2^2) + (sz*(2*s2*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s2^2)^2, (2*sxy*(2*s2*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s2^2)^2 - (2*s2 - 2*sz)/(J2 - 3*s2^2) + (((2*sxy)/(J2 - 3*s2^2) + (6*s2*(2*s2*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s2^2)^2)*(2*s2*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s2^2), (2*syz*(2*s2*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s2^2)^2 - (2*szx)/(J2 - 3*s2^2) + (((2*sxy)/(J2 - 3*s2^2) + (6*s2*(2*s2*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s2^2)^2)*(2*s2*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s2^2), (2*szx*(2*s2*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s2^2)^2 - (2*syz)/(J2 - 3*s2^2) + (((2*sxy)/(J2 - 3*s2^2) + (6*s2*(2*s2*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s2^2)^2)*(2*s2*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s2^2);
         (4*syz)/(3*(J2 - 3*s2^2)) + (((2*syz)/(J2 - 3*s2^2) + (6*s2*(2*s2*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s2^2)^2)*(J2/3 + s2*sx + sy*sz - syz^2))/(J2 - 3*s2^2) + (sx*(2*s2*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s2^2)^2, (((2*syz)/(J2 - 3*s2^2) + (6*s2*(2*s2*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s2^2)^2)*(J2/3 + s2*sy + sx*sz - szx^2))/(J2 - 3*s2^2) - (2*syz)/(3*(J2 - 3*s2^2)) + (sy*(2*s2*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s2^2)^2, (((2*syz)/(J2 - 3*s2^2) + (6*s2*(2*s2*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s2^2)^2)*(J2/3 + s2*sz + sx*sy - sxy^2))/(J2 - 3*s2^2) - (2*syz)/(3*(J2 - 3*s2^2)) + (sz*(2*s2*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s2^2)^2, (2*sxy*(2*s2*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s2^2)^2 - (2*szx)/(J2 - 3*s2^2) + (((2*syz)/(J2 - 3*s2^2) + (6*s2*(2*s2*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s2^2)^2)*(2*s2*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s2^2), (2*syz*(2*s2*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s2^2)^2 - (2*s2 - 2*sx)/(J2 - 3*s2^2) + (((2*syz)/(J2 - 3*s2^2) + (6*s2*(2*s2*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s2^2)^2)*(2*s2*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s2^2), (2*szx*(2*s2*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s2^2)^2 - (2*sxy)/(J2 - 3*s2^2) + (((2*syz)/(J2 - 3*s2^2) + (6*s2*(2*s2*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s2^2)^2)*(2*s2*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s2^2);
         (((2*szx)/(J2 - 3*s2^2) + (6*s2*(2*s2*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s2^2)^2)*(J2/3 + s2*sx + sy*sz - syz^2))/(J2 - 3*s2^2) - (2*szx)/(3*(J2 - 3*s2^2)) + (sx*(2*s2*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s2^2)^2, (4*szx)/(3*(J2 - 3*s2^2)) + (((2*szx)/(J2 - 3*s2^2) + (6*s2*(2*s2*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s2^2)^2)*(J2/3 + s2*sy + sx*sz - szx^2))/(J2 - 3*s2^2) + (sy*(2*s2*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s2^2)^2, (((2*szx)/(J2 - 3*s2^2) + (6*s2*(2*s2*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s2^2)^2)*(J2/3 + s2*sz + sx*sy - sxy^2))/(J2 - 3*s2^2) - (2*szx)/(3*(J2 - 3*s2^2)) + (sz*(2*s2*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s2^2)^2, (2*sxy*(2*s2*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s2^2)^2 - (2*syz)/(J2 - 3*s2^2) + (((2*szx)/(J2 - 3*s2^2) + (6*s2*(2*s2*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s2^2)^2)*(2*s2*sxy - 2*sxy*sz + 2*syz*szx))/(J2 - 3*s2^2), (2*syz*(2*s2*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s2^2)^2 - (2*sxy)/(J2 - 3*s2^2) + (((2*szx)/(J2 - 3*s2^2) + (6*s2*(2*s2*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s2^2)^2)*(2*s2*syz - 2*sx*syz + 2*sxy*szx))/(J2 - 3*s2^2), (2*szx*(2*s2*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s2^2)^2 - (2*s2 - 2*sy)/(J2 - 3*s2^2) + (((2*szx)/(J2 - 3*s2^2) + (6*s2*(2*s2*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s2^2)^2)*(2*s2*szx + 2*sxy*syz - 2*sy*szx))/(J2 - 3*s2^2)];
ddGddS=dXGdS*ddGddX*dXGdS.'+ddXGddS1*dGdX(1)+ddXGddS2*dGdX(2);
end

function strain_eq=calculate_equivalent_strain(strain)
strain_eq=(strain(1)-strain(2)).^2+(strain(2)-strain(3)).^2+(strain(3)-strain(1)).^2+(strain(4).^2+strain(5).^2+strain(6).^2)*1.5;
strain_eq=sqrt(2/9*strain_eq);
end

